INSERT INTO `PIZZA` VALUES (null, 'pizdarita', 'pizdowata', true, 20.00, 10, 'TUESDAY');
INSERT INTO `PIZZA` VALUES (null, 'gownorita', 'gowniana', true, 0.02, 9, 'WEDNESDAY');
INSERT INTO `PIZZA` VALUES (null, 'ciparita', 'cipowata', false, 420.68, 8, 'THURSDAY');
INSERT INTO `PIZZA` VALUES (null, 'srakarita', 'wysrana', true, 450.02, 9, 'FRIDAY');
INSERT INTO `SAUCE` VALUES (null, 'sosowy', false, 2.98, 0, 'WEDNESDAY');
INSERT INTO `SAUCE` VALUES (null, 'niesosowy', true, 2.88, 1, 'SUNDAY');
INSERT INTO `SAUCE` VALUES (null, 'podsosowy', false, 0.02, 2, 'MONDAY');
INSERT INTO `SAUCE` VALUES (null, 'nadsosowy', true, 8.20, 3, 'TUESDAY');
INSERT INTO `DRINK` VALUES (null, 'Piss', 8.22, 5, 'WEDNESDAY');
INSERT INTO `DRINK` VALUES (null, 'Semen', 10.00, 6, 'THURSDAY');
INSERT INTO `DRINK` VALUES (null, 'Goo',  0.06, 7, 'FRIDAY');
INSERT INTO `DRINK` VALUES (null, 'Liquid shit', 5.02, 8, 'SATURDAY');
INSERT INTO `USER` VALUES (null, 'Szymon', 'Skowronski', 'emialSzymona', 'telefonSzymona', 'loginszymona', 'hasloszymona');
INSERT INTO `USER` VALUES (null, 'Jacek', 'Szwed', 'emialJacka', 'telefonJacka', 'loginjacka', 'haslojacka');
INSERT INTO `TITLE` VALUES (null, 'Gej');
INSERT INTO `TITLE` VALUES (null, 'MegaGej');
INSERT INTO `COOK` VALUES (null, 'Kacper', 'Kwiatkowski', 1, 'kacper@sraka.pl', '666 666 666');
INSERT INTO `COOK` VALUES (null, 'Bartlomiej', 'Banaszak', 2, 'bartlomiej@sraka.pl', '669 669 669');

INSERT INTO `PIZZA` VALUES (null, 'margherita', 'Mozarella, ziołowy sos pomidorowy', true, 36.98, 6, 'TUESDAY', 'img/pizza/margeritha.PNG');
INSERT INTO `PIZZA` VALUES (null, 'pepperoni', 'Pepperoni, mozarella, ziołowy sos pomidorowy', false, 42.68, 8, 'TUESDAY', 'img/pizza/pepperoni.jpg');
INSERT INTO `PIZZA` VALUES (null, 'hawajska', 'Szynka, ananas, ser mozarella, ziołowy sos pomidorowy', false, 200.00, 1, 'MONDAY', 'img/pizza/hawajska.jpg');
INSERT INTO `PIZZA` VALUES (null, 'classica', 'Szynka, pieczarki, ser mozarella, ziołowy sos pomidorowy', false, 42.30, 10, 'WEDNESDAY', 'img/pizza/classica.jpg');
INSERT INTO `PIZZA` VALUES (null, 'americana', 'Sos pomidorowy, Mozzarella, Pieczarki, Pomidory koktajlowe', true, 41.30, 7, 'WEDNESDAY', 'img/pizza/americana.jpg');
INSERT INTO `PIZZA` VALUES (null, 'teksas', 'Sos BBQ, Mozzarella, Kurczak, Kukurydza, Cebula czerwona', false, 47.32, 5, 'FRIDAY', 'img/pizza/texas.jpg');
INSERT INTO `PIZZA` VALUES (null, 'europejska', 'Sos pomidorowy, Mozzarella, Szynka, Wołowina, Pieczarki', false, 46.42, 3, 'SUNDAY', 'img/pizza/europejska.jpg');
INSERT INTO `PIZZA` VALUES (null, 'hot pepperoni', 'Mozzarella, Pepperoni, Jalapenos, Cebula czerwona', false, 44.98, 10, 'SUNDAY','img/pizza/hot_pepperoni.png');
INSERT INTO `PIZZA` VALUES (null, 'supreme', 'Sos pomidorowy, Mozzarella, Pepperoni, Wołowina, Zielona papryka, Pieczarki, Cebula czerwona', false, 49.20, 7, 'MONDAY', 'img/pizza/supreme.jpg');
INSERT INTO `PIZZA` VALUES (null, 'farmerska', 'Sos pomidorowy, Mozzarella, Kurczak, Zielona papryka, Pieczarki, Cebula czerwona', false, 60.32, 10, 'TUESDAY', 'img/pizza/farmerska.png');
INSERT INTO `PIZZA` VALUES (null, 'mięsna', 'Sos pomidorowy, Mozzarella, Pepperoni, Wołowina, Wieprzowina', false, 50.24, 8, 'FRIDAY', 'img/pizza/miesna.jpg');
INSERT INTO `PIZZA` VALUES (null, 'capricciosa', 'Sos pomidorowy, Mozzarella, Szynka, Oliwki czarne, Pieczarki, Pomidory koktajlowe', false, 39.98, 9, 'SATURDAY', 'img/pizza/capricciosa.jpg');
INSERT INTO `PIZZA` VALUES (null, 'carbonara', 'Sos biały, Mozzarella, Boczek, Pomidory, Pieczarki, Cebula czerwona', false, 54.48, 6, 'SATURDAY','img/pizza/carbonara.jpg');
INSERT INTO `PIZZA` VALUES (null, 'super supreme', 'Sos pomidorowy, Mozzarella, Pepperoni, Szynka, Wołowina, Wieprzowina, Zielona papryka, Oliwki czarne, Pieczarki, Cebula czerwona', false, 60.36, 10, 'FRIDAY', 'img/pizza/super_supreme.jpg');
INSERT INTO `PIZZA` VALUES (null, 'prosciutto e rucola', 'Sos pomidorowy, Mozzarella, Pomidory koktajlowe, Corregio, Rukola, Świeża mozzarella, Szynka dojrzewająca', false, 50.00, 4, 'FRIDAY', 'img/pizza/prosciutto_e_rucola.jpg');
INSERT INTO `PIZZA` VALUES (null, 'vege mania', 'Sos pomidorowy, Mozzarella, Pieczarki, Cebula czerwona, Pomidory koktajlowe, Kolorowa papryka, Corregio, Świeża mozzarella, Szpinak świeży', true, 450.02, 8, 'THURSDAY', 'img/pizza/vege_mania.jpg');
INSERT INTO `PIZZA` VALUES (null, 'double bacon burger', 'sos BBQ, mozzarella, podwójna porcja wędzonego boczku, wołowina, sos majonezowy na wierzchu', false, 39.98, 6, 'TUESDAY', 'img/pizza/double_bacon_burger.jpg');
INSERT INTO `PIZZA` VALUES (null, 'new yorker', 'sos pomidorowy, mozzarella, pepperoni, szynka, boczek, pieczarki', false, 45.30, 9, 'MONDAY', 'img/pizza/new_yorker.jpg');
INSERT INTO `PIZZA` VALUES (null, 'tex-mex', 'sos pomidorowy, mozzarella, pikantne papryczki jalapeño, płatki chili, czerwona fasola, kukurydza, wołowina, cebula, papryka, sos salsa Mexicana na wierzchu', false, 55.70, 9, 'SUNDAY', 'img/pizza/tex-mex.jpg');
INSERT INTO `PIZZA` VALUES (null, 'prowansalska', 'sos śmietanowy, mozzarella, młody szpinak, suszone pomidory, cebula, papryka, czarne oliwki, zioła prowansalskie', true, 42.34, 5, 'THURSDAY','img/pizza/prowansalska.jpg');
INSERT INTO `PIZZA` VALUES (null, 'cztery sery', 'sos śmietanowy, mozzarella, cheddar, ementalski, pleśniowy Lazur', true, 40.00, 8, 'WEDNESDAY', 'img/pizza/cztery_sery.jpg');
INSERT INTO `PIZZA` VALUES (null, 'hypnotica', 'sos śmietanowy, mozzarella, szpinak, pepperoni, wędzony boczek, wołowina, cebula, sauerkraut, sos BBQ na wierzchu', false, 69.96, 10, 'SATURDAY', 'img/pizza/hypnotica.jpg');
INSERT INTO `PIZZA` VALUES (null, 'corny', 'sos pomidorowy, mozarella, kukurydza, pieczarki, szynka', false, 48.90, 10, 'SATURDAY', 'img/pizza/corny.png');
INSERT INTO `PIZZA` VALUES (null, 'Neapoletana', 'sos pomidorowy, mozarella, oliwa z oliwek, parmezan, świeża bazylia', true, 34.80, 6, 'THURSDAY', 'img/pizza/neapoletana.jpg');
INSERT INTO `PIZZA` VALUES (null, 'Toscana', 'sos pomidorowy, ser mozzarella, szynka, salami, papryka, pieczarki, kukurydza, świeża bazylia', false, 38.28, 8, 'MONDAY', 'img/pizza/toscana.jpg');
INSERT INTO `PIZZA` VALUES (null, 'Di Casa', 'sos pomidorowy, ser mozzarella, szynka, pieczarki, świeży pomidor, oregano, świeża bazylia', false, 38.28, 7, 'WEDNESDAY', 'img/pizza/di_casa.jpg');
INSERT INTO `PIZZA` VALUES (null, 'Mafiosa', 'sos pomidorowy, ser mozzarella, boczek wędzony, pieczarki, czerwona cebula, oregano', false, 40.68, 9, 'SUNDAY', 'img/pizza/mafiosa.jpg');
INSERT INTO `PIZZA` VALUES (null, 'Spinacci', 'sos pomidorowy, ser mozzarella, szpinak, cebula, płatki świeżego czosnku, świeży pomidor, świeży rozmaryn', true, 39.96, 4, 'THURSDAY', 'img/pizza/spinacci.jpg');

INSERT INTO `SAUCE` VALUES (null, 'ziołowy', true, 3.88, 6, 'THURSDAY');
INSERT INTO `SAUCE` VALUES (null, 'czosnkowy', true, 3.00, 10, 'SATURDAY');
INSERT INTO `SAUCE` VALUES (null, 'bbq', false, 4.20, 7, 'MONDAY');
INSERT INTO `SAUCE` VALUES (null, 'ostry', true, 3.40, 9, 'SUNDAY');
INSERT INTO `SAUCE` VALUES (null, 'ketchup', true, 2.40, 6, 'TUESDAY');
INSERT INTO `SAUCE` VALUES (null, 'gyros', false, 4.80, 5, 'WEDNESDAY');
INSERT INTO `SAUCE` VALUES (null, 'śmietanowy', true, 3.44, 3, 'FRIDAY');
INSERT INTO `DRINK` VALUES (null, 'Cola', 5, 10, 'WEDNESDAY');
INSERT INTO `DRINK` VALUES (null, '7up', 4.20, 6, 'MONDAY');
INSERT INTO `DRINK` VALUES (null, 'Pepsi',  5.20, 9, 'FRIDAY');
INSERT INTO `DRINK` VALUES (null, 'Woda',  2.32, 10, 'THURSDAY');
INSERT INTO `DRINK` VALUES (null, 'Fanta',  4.40, 7, 'TUESDAY');
INSERT INTO `DRINK` VALUES (null, 'Piwo Carlsberg',  6.00, 8, 'SUNDAY');
INSERT INTO `DRINK` VALUES (null, 'Piwo Perła Export', 3.80, 10, 'SATURDAY');
INSERT INTO `USER` VALUES (null, 'Szymon', 'Skowronski', 'szymon.skowronski@gmail.com', '666420869', 'sazerasty', 'ccc37b8996b6b89ba3cee0e88b81cabf','Poznan','63-349','Skowronkowa/32');
INSERT INTO `USER` VALUES (null, 'Bartosz', 'Banasiak', 'bartosz.banasiak@gmail.com', '607433298', 'tolereq', 'd4f0229dc7b1000797a2f29d892d81bd','Poznan','61-398','Rudzikowa/48');
INSERT INTO `USER` VALUES (null, 'Kacper', 'Kwietniewski', 'kacper.kwietniewski@gmail.com', '598374789', 'k3t3k', '98c7f3e214c7b7aaf6a7bb4a523b8e4e','Poznan','60-512','Kwiatkowska/27');
INSERT INTO `USER` VALUES (null, 'Jacek', 'Szwed', 'jacek.szwed@gmail.com', '709478897', 'szwedkasta', '1d740076f36da8ac5dc1bc70c77a7a7b','Poznan','62-294','Szwedniewska/1');
INSERT INTO `USER` VALUES (null, 'Damian', 'Stolarski', 'damian.stolarski@zsl.poznan.pl', '509666509', 'damianostolano', '0f0934c398fe001f2ca5d7e580976cd6','Rzym','42-038','Milano/122');
INSERT INTO `TITLE` VALUES (null, 'Vege Master');
INSERT INTO `TITLE` VALUES (null, 'Spicy As Hell');
INSERT INTO `TITLE` VALUES (null, 'The Butcher');
INSERT INTO `TITLE` VALUES (null, 'Tomato Lover');
INSERT INTO `TITLE` VALUES (null, 'Simple As That');
INSERT INTO `COOK` VALUES (null, 'Kacperro', 'Kwiatkowski', 1, 'kacperrokwiatesko@kssr.pl', '897345652');
INSERT INTO `COOK` VALUES (null, 'Bartolomeo', 'Banaszak', 3, 'bartolomeo@kssr.pl', '58999773');
INSERT INTO `COOK` VALUES (null, 'Al', 'Paccino', 2, 'alpaccino@kssr.pl', '685465732');
INSERT INTO `COOK` VALUES (null, 'Damiano', 'Maccaroni', 4, 'maccaronid@kssr.pl', '765345666');
INSERT INTO `COOK` VALUES (null, 'Jacenty', 'Szwedniewski', 3, 'jacenty.sz@kssr.pl', '555463763');
INSERT INTO `COOK` VALUES (null, 'Simone', 'Skowrone', 5, 'simoneskowrone@kssr.pl', '687777746');